# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mujoco_ros_msgs/GetGeomPropertiesRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetGeomPropertiesRequest(genpy.Message):
  _md5sum = "57f0d4c01a52c15d5869d247260c475c"
  _type = "mujoco_ros_msgs/GetGeomPropertiesRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string geom_name
string admin_hash
"""
  __slots__ = ['geom_name','admin_hash']
  _slot_types = ['string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       geom_name,admin_hash

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetGeomPropertiesRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.geom_name is None:
        self.geom_name = ''
      if self.admin_hash is None:
        self.admin_hash = ''
    else:
      self.geom_name = ''
      self.admin_hash = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.geom_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.admin_hash
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.geom_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.geom_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.admin_hash = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.admin_hash = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.geom_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.admin_hash
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.geom_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.geom_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.admin_hash = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.admin_hash = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mujoco_ros_msgs/GetGeomPropertiesResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mujoco_ros_msgs.msg

class GetGeomPropertiesResponse(genpy.Message):
  _md5sum = "55ee8b0f1aee0c42a9390bea52b5aefb"
  _type = "mujoco_ros_msgs/GetGeomPropertiesResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """mujoco_ros_msgs/GeomProperties properties
bool success
string status_message


================================================================================
MSG: mujoco_ros_msgs/GeomProperties
string name
mujoco_ros_msgs/GeomType type
float32 body_mass # total mass of the body this geom belongs to
float32 size_0
float32 size_1
float32 size_2
float32 friction_slide
float32 friction_spin
float32 friction_roll

================================================================================
MSG: mujoco_ros_msgs/GeomType
uint16 value
uint16 PLANE=0
uint16 HFIELD=1
uint16 SPHERE=2
uint16 CAPSULE=3
uint16 ELLIPSOID=4
uint16 CYLINDER=5
uint16 BOX=6
uint16 MESH=7
uint16 GEOM_NONE = 1001
"""
  __slots__ = ['properties','success','status_message']
  _slot_types = ['mujoco_ros_msgs/GeomProperties','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       properties,success,status_message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetGeomPropertiesResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.properties is None:
        self.properties = mujoco_ros_msgs.msg.GeomProperties()
      if self.success is None:
        self.success = False
      if self.status_message is None:
        self.status_message = ''
    else:
      self.properties = mujoco_ros_msgs.msg.GeomProperties()
      self.success = False
      self.status_message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.properties.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H7fB().pack(_x.properties.type.value, _x.properties.body_mass, _x.properties.size_0, _x.properties.size_1, _x.properties.size_2, _x.properties.friction_slide, _x.properties.friction_spin, _x.properties.friction_roll, _x.success))
      _x = self.status_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.properties is None:
        self.properties = mujoco_ros_msgs.msg.GeomProperties()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.properties.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.properties.name = str[start:end]
      _x = self
      start = end
      end += 31
      (_x.properties.type.value, _x.properties.body_mass, _x.properties.size_0, _x.properties.size_1, _x.properties.size_2, _x.properties.friction_slide, _x.properties.friction_spin, _x.properties.friction_roll, _x.success,) = _get_struct_H7fB().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status_message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status_message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.properties.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H7fB().pack(_x.properties.type.value, _x.properties.body_mass, _x.properties.size_0, _x.properties.size_1, _x.properties.size_2, _x.properties.friction_slide, _x.properties.friction_spin, _x.properties.friction_roll, _x.success))
      _x = self.status_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.properties is None:
        self.properties = mujoco_ros_msgs.msg.GeomProperties()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.properties.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.properties.name = str[start:end]
      _x = self
      start = end
      end += 31
      (_x.properties.type.value, _x.properties.body_mass, _x.properties.size_0, _x.properties.size_1, _x.properties.size_2, _x.properties.friction_slide, _x.properties.friction_spin, _x.properties.friction_roll, _x.success,) = _get_struct_H7fB().unpack(str[start:end])
      self.success = bool(self.success)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status_message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status_message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_H7fB = None
def _get_struct_H7fB():
    global _struct_H7fB
    if _struct_H7fB is None:
        _struct_H7fB = struct.Struct("<H7fB")
    return _struct_H7fB
class GetGeomProperties(object):
  _type          = 'mujoco_ros_msgs/GetGeomProperties'
  _md5sum = '39732699bb1604377c28257f0fc466f2'
  _request_class  = GetGeomPropertiesRequest
  _response_class = GetGeomPropertiesResponse
