// Generated by gencpp from file mujoco_ros_msgs/EqualityConstraintParameters.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_EQUALITYCONSTRAINTPARAMETERS_H
#define MUJOCO_ROS_MSGS_MESSAGE_EQUALITYCONSTRAINTPARAMETERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mujoco_ros_msgs/EqualityConstraintType.h>
#include <mujoco_ros_msgs/SolverParameters.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Pose.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct EqualityConstraintParameters_
{
  typedef EqualityConstraintParameters_<ContainerAllocator> Type;

  EqualityConstraintParameters_()
    : name()
    , type()
    , solverParameters()
    , active(false)
    , classParam()
    , element1()
    , element2()
    , torquescale(0.0)
    , anchor()
    , relpose()
    , polycoef()  {
    }
  EqualityConstraintParameters_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , type(_alloc)
    , solverParameters(_alloc)
    , active(false)
    , classParam(_alloc)
    , element1(_alloc)
    , element2(_alloc)
    , torquescale(0.0)
    , anchor(_alloc)
    , relpose(_alloc)
    , polycoef(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef  ::mujoco_ros_msgs::SolverParameters_<ContainerAllocator>  _solverParameters_type;
  _solverParameters_type solverParameters;

   typedef uint8_t _active_type;
  _active_type active;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _classParam_type;
  _classParam_type classParam;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _element1_type;
  _element1_type element1;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _element2_type;
  _element2_type element2;

   typedef double _torquescale_type;
  _torquescale_type torquescale;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _anchor_type;
  _anchor_type anchor;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _relpose_type;
  _relpose_type relpose;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _polycoef_type;
  _polycoef_type polycoef;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> const> ConstPtr;

}; // struct EqualityConstraintParameters_

typedef ::mujoco_ros_msgs::EqualityConstraintParameters_<std::allocator<void> > EqualityConstraintParameters;

typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintParameters > EqualityConstraintParametersPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintParameters const> EqualityConstraintParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.type == rhs.type &&
    lhs.solverParameters == rhs.solverParameters &&
    lhs.active == rhs.active &&
    lhs.classParam == rhs.classParam &&
    lhs.element1 == rhs.element1 &&
    lhs.element2 == rhs.element2 &&
    lhs.torquescale == rhs.torquescale &&
    lhs.anchor == rhs.anchor &&
    lhs.relpose == rhs.relpose &&
    lhs.polycoef == rhs.polycoef;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "152c371cf6b748601a865ee2d968aec7";
  }

  static const char* value(const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x152c371cf6b74860ULL;
  static const uint64_t static_value2 = 0x1a865ee2d968aec7ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/EqualityConstraintParameters";
  }

  static const char* value(const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"mujoco_ros_msgs/EqualityConstraintType type\n"
"mujoco_ros_msgs/SolverParameters solverParameters\n"
"bool active\n"
"string classParam\n"
"string element1\n"
"string element2\n"
"float64 torquescale\n"
"geometry_msgs/Vector3 anchor\n"
"geometry_msgs/Pose relpose\n"
"float64[] polycoef\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/EqualityConstraintType\n"
"uint16 value\n"
"uint16 CONNECT=0\n"
"uint16 WELD=1\n"
"uint16 JOINT=2\n"
"uint16 TENDON=3\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/SolverParameters\n"
"# solimp parameters\n"
"\n"
"float64 dmin\n"
"float64 dmax\n"
"float64 width\n"
"float64 midpoint\n"
"float64 power\n"
"\n"
"# solref parameters\n"
"\n"
"float64 timeconst\n"
"float64 dampratio\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.type);
      stream.next(m.solverParameters);
      stream.next(m.active);
      stream.next(m.classParam);
      stream.next(m.element1);
      stream.next(m.element2);
      stream.next(m.torquescale);
      stream.next(m.anchor);
      stream.next(m.relpose);
      stream.next(m.polycoef);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EqualityConstraintParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "solverParameters: ";
    Printer< ::mujoco_ros_msgs::SolverParameters_<ContainerAllocator> >::stream(s, indent + "  ", v.solverParameters);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "classParam: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.classParam);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "element1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.element1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "element2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.element2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "torquescale: ";
    Printer<double>::stream(s, indent + "  ", v.torquescale);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "anchor: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.anchor);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "relpose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.relpose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "polycoef: ";
    if (v.polycoef.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.polycoef.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.polycoef[i]);
    }
    if (v.polycoef.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_EQUALITYCONSTRAINTPARAMETERS_H
