// Generated by gencpp from file mujoco_ros_msgs/EqualityConstraintType.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_EQUALITYCONSTRAINTTYPE_H
#define MUJOCO_ROS_MSGS_MESSAGE_EQUALITYCONSTRAINTTYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct EqualityConstraintType_
{
  typedef EqualityConstraintType_<ContainerAllocator> Type;

  EqualityConstraintType_()
    : value(0)  {
    }
  EqualityConstraintType_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint16_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CONNECT)
  #undef CONNECT
#endif
#if defined(_WIN32) && defined(WELD)
  #undef WELD
#endif
#if defined(_WIN32) && defined(JOINT)
  #undef JOINT
#endif
#if defined(_WIN32) && defined(TENDON)
  #undef TENDON
#endif

  enum {
    CONNECT = 0u,
    WELD = 1u,
    JOINT = 2u,
    TENDON = 3u,
  };


  typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> const> ConstPtr;

}; // struct EqualityConstraintType_

typedef ::mujoco_ros_msgs::EqualityConstraintType_<std::allocator<void> > EqualityConstraintType;

typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintType > EqualityConstraintTypePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::EqualityConstraintType const> EqualityConstraintTypeConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e70314e6b4684677c8a1025a8bc5ef88";
  }

  static const char* value(const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe70314e6b4684677ULL;
  static const uint64_t static_value2 = 0xc8a1025a8bc5ef88ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/EqualityConstraintType";
  }

  static const char* value(const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 value\n"
"uint16 CONNECT=0\n"
"uint16 WELD=1\n"
"uint16 JOINT=2\n"
"uint16 TENDON=3\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EqualityConstraintType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::EqualityConstraintType_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_EQUALITYCONSTRAINTTYPE_H
