// Generated by gencpp from file mujoco_ros_msgs/GetBodyState.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETBODYSTATE_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETBODYSTATE_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/GetBodyStateRequest.h>
#include <mujoco_ros_msgs/GetBodyStateResponse.h>


namespace mujoco_ros_msgs
{

struct GetBodyState
{

typedef GetBodyStateRequest Request;
typedef GetBodyStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBodyState
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::GetBodyState > {
  static const char* value()
  {
    return "0322b483548cedc01d60d344a6aee68f";
  }

  static const char* value(const ::mujoco_ros_msgs::GetBodyState&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::GetBodyState > {
  static const char* value()
  {
    return "mujoco_ros_msgs/GetBodyState";
  }

  static const char* value(const ::mujoco_ros_msgs::GetBodyState&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::GetBodyStateRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetBodyState >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetBodyStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetBodyStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetBodyStateRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetBodyState >
template<>
struct DataType< ::mujoco_ros_msgs::GetBodyStateRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetBodyStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::GetBodyStateResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetBodyState >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetBodyStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetBodyStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetBodyStateResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetBodyState >
template<>
struct DataType< ::mujoco_ros_msgs::GetBodyStateResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetBodyStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETBODYSTATE_H
