// Generated by gencpp from file mujoco_ros_msgs/GetEqualityConstraintParametersResponse.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERSRESPONSE_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mujoco_ros_msgs/EqualityConstraintParameters.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct GetEqualityConstraintParametersResponse_
{
  typedef GetEqualityConstraintParametersResponse_<ContainerAllocator> Type;

  GetEqualityConstraintParametersResponse_()
    : parameters()
    , success(false)
    , status_message()  {
    }
  GetEqualityConstraintParametersResponse_(const ContainerAllocator& _alloc)
    : parameters(_alloc)
    , success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >> _parameters_type;
  _parameters_type parameters;

   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetEqualityConstraintParametersResponse_

typedef ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<std::allocator<void> > GetEqualityConstraintParametersResponse;

typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse > GetEqualityConstraintParametersResponsePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse const> GetEqualityConstraintParametersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator2> & rhs)
{
  return lhs.parameters == rhs.parameters &&
    lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4bc2567aa5743b76b83fbbdda3b79ff";
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4bc2567aa5743b7ULL;
  static const uint64_t static_value2 = 0x6b83fbbdda3b79ffULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/GetEqualityConstraintParametersResponse";
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/EqualityConstraintParameters[] parameters\n"
"bool success\n"
"string status_message\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/EqualityConstraintParameters\n"
"string name\n"
"mujoco_ros_msgs/EqualityConstraintType type\n"
"mujoco_ros_msgs/SolverParameters solverParameters\n"
"bool active\n"
"string classParam\n"
"string element1\n"
"string element2\n"
"float64 torquescale\n"
"geometry_msgs/Vector3 anchor\n"
"geometry_msgs/Pose relpose\n"
"float64[] polycoef\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/EqualityConstraintType\n"
"uint16 value\n"
"uint16 CONNECT=0\n"
"uint16 WELD=1\n"
"uint16 JOINT=2\n"
"uint16 TENDON=3\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/SolverParameters\n"
"# solimp parameters\n"
"\n"
"float64 dmin\n"
"float64 dmax\n"
"float64 width\n"
"float64 midpoint\n"
"float64 power\n"
"\n"
"# solref parameters\n"
"\n"
"float64 timeconst\n"
"float64 dampratio\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameters);
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEqualityConstraintParametersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "parameters: ";
    if (v.parameters.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::mujoco_ros_msgs::EqualityConstraintParameters_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.parameters[i]);
    }
    if (v.parameters.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERSRESPONSE_H
