// Generated by gencpp from file mujoco_ros_msgs/GetEqualityConstraintParametersRequest.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERSREQUEST_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct GetEqualityConstraintParametersRequest_
{
  typedef GetEqualityConstraintParametersRequest_<ContainerAllocator> Type;

  GetEqualityConstraintParametersRequest_()
    : names()
    , admin_hash()  {
    }
  GetEqualityConstraintParametersRequest_(const ContainerAllocator& _alloc)
    : names(_alloc)
    , admin_hash(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _admin_hash_type;
  _admin_hash_type admin_hash;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetEqualityConstraintParametersRequest_

typedef ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<std::allocator<void> > GetEqualityConstraintParametersRequest;

typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest > GetEqualityConstraintParametersRequestPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest const> GetEqualityConstraintParametersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names &&
    lhs.admin_hash == rhs.admin_hash;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce965b3c89ce5bffbdbd324e772bc868";
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce965b3c89ce5bffULL;
  static const uint64_t static_value2 = 0xbdbd324e772bc868ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/GetEqualityConstraintParametersRequest";
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n"
"string admin_hash\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
      stream.next(m.admin_hash);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEqualityConstraintParametersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "names: ";
    if (v.names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.names[i]);
    }
    if (v.names.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "admin_hash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.admin_hash);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERSREQUEST_H
