// Generated by gencpp from file mujoco_ros_msgs/GetEqualityConstraintParameters.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERS_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERS_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/GetEqualityConstraintParametersRequest.h>
#include <mujoco_ros_msgs/GetEqualityConstraintParametersResponse.h>


namespace mujoco_ros_msgs
{

struct GetEqualityConstraintParameters
{

typedef GetEqualityConstraintParametersRequest Request;
typedef GetEqualityConstraintParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEqualityConstraintParameters
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParameters > {
  static const char* value()
  {
    return "282e8dd7ae13e3ddf31cbad398a879a7";
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParameters&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::GetEqualityConstraintParameters > {
  static const char* value()
  {
    return "mujoco_ros_msgs/GetEqualityConstraintParameters";
  }

  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParameters&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParameters >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetEqualityConstraintParameters >
template<>
struct DataType< ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParameters >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetEqualityConstraintParameters >
template<>
struct DataType< ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetEqualityConstraintParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETEQUALITYCONSTRAINTPARAMETERS_H
