// Generated by gencpp from file mujoco_ros_msgs/GetGeomPropertiesRequest.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETGEOMPROPERTIESREQUEST_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETGEOMPROPERTIESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct GetGeomPropertiesRequest_
{
  typedef GetGeomPropertiesRequest_<ContainerAllocator> Type;

  GetGeomPropertiesRequest_()
    : geom_name()
    , admin_hash()  {
    }
  GetGeomPropertiesRequest_(const ContainerAllocator& _alloc)
    : geom_name(_alloc)
    , admin_hash(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _geom_name_type;
  _geom_name_type geom_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _admin_hash_type;
  _admin_hash_type admin_hash;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGeomPropertiesRequest_

typedef ::mujoco_ros_msgs::GetGeomPropertiesRequest_<std::allocator<void> > GetGeomPropertiesRequest;

typedef boost::shared_ptr< ::mujoco_ros_msgs::GetGeomPropertiesRequest > GetGeomPropertiesRequestPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::GetGeomPropertiesRequest const> GetGeomPropertiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.geom_name == rhs.geom_name &&
    lhs.admin_hash == rhs.admin_hash;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57f0d4c01a52c15d5869d247260c475c";
  }

  static const char* value(const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57f0d4c01a52c15dULL;
  static const uint64_t static_value2 = 0x5869d247260c475cULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/GetGeomPropertiesRequest";
  }

  static const char* value(const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string geom_name\n"
"string admin_hash\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.geom_name);
      stream.next(m.admin_hash);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGeomPropertiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::GetGeomPropertiesRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "geom_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.geom_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "admin_hash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.admin_hash);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETGEOMPROPERTIESREQUEST_H
