// Generated by gencpp from file mujoco_ros_msgs/GetPluginStats.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETPLUGINSTATS_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETPLUGINSTATS_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/GetPluginStatsRequest.h>
#include <mujoco_ros_msgs/GetPluginStatsResponse.h>


namespace mujoco_ros_msgs
{

struct GetPluginStats
{

typedef GetPluginStatsRequest Request;
typedef GetPluginStatsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPluginStats
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::GetPluginStats > {
  static const char* value()
  {
    return "7d3043450de18344352d2d333c449deb";
  }

  static const char* value(const ::mujoco_ros_msgs::GetPluginStats&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::GetPluginStats > {
  static const char* value()
  {
    return "mujoco_ros_msgs/GetPluginStats";
  }

  static const char* value(const ::mujoco_ros_msgs::GetPluginStats&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::GetPluginStatsRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetPluginStats >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetPluginStatsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetPluginStats >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetPluginStatsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetPluginStatsRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetPluginStats >
template<>
struct DataType< ::mujoco_ros_msgs::GetPluginStatsRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetPluginStats >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetPluginStatsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::GetPluginStatsResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetPluginStats >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetPluginStatsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetPluginStats >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetPluginStatsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetPluginStatsResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetPluginStats >
template<>
struct DataType< ::mujoco_ros_msgs::GetPluginStatsResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetPluginStats >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetPluginStatsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETPLUGINSTATS_H
