// Generated by gencpp from file mujoco_ros_msgs/GetSimInfo.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETSIMINFO_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETSIMINFO_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/GetSimInfoRequest.h>
#include <mujoco_ros_msgs/GetSimInfoResponse.h>


namespace mujoco_ros_msgs
{

struct GetSimInfo
{

typedef GetSimInfoRequest Request;
typedef GetSimInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSimInfo
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::GetSimInfo > {
  static const char* value()
  {
    return "9d1bcf43ea2e10aaf5f5745e953cd88d";
  }

  static const char* value(const ::mujoco_ros_msgs::GetSimInfo&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::GetSimInfo > {
  static const char* value()
  {
    return "mujoco_ros_msgs/GetSimInfo";
  }

  static const char* value(const ::mujoco_ros_msgs::GetSimInfo&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::GetSimInfoRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetSimInfo >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetSimInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetSimInfo >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetSimInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetSimInfoRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetSimInfo >
template<>
struct DataType< ::mujoco_ros_msgs::GetSimInfoRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetSimInfo >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetSimInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::GetSimInfoResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetSimInfo >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetSimInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetSimInfo >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetSimInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetSimInfoResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetSimInfo >
template<>
struct DataType< ::mujoco_ros_msgs::GetSimInfoResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetSimInfo >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetSimInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETSIMINFO_H
