// Generated by gencpp from file mujoco_ros_msgs/GetStateUint.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETSTATEUINT_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETSTATEUINT_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/GetStateUintRequest.h>
#include <mujoco_ros_msgs/GetStateUintResponse.h>


namespace mujoco_ros_msgs
{

struct GetStateUint
{

typedef GetStateUintRequest Request;
typedef GetStateUintResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetStateUint
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::GetStateUint > {
  static const char* value()
  {
    return "e15f8271e1c8147c518f22f4076ebd9c";
  }

  static const char* value(const ::mujoco_ros_msgs::GetStateUint&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::GetStateUint > {
  static const char* value()
  {
    return "mujoco_ros_msgs/GetStateUint";
  }

  static const char* value(const ::mujoco_ros_msgs::GetStateUint&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::GetStateUintRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetStateUint >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetStateUintRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetStateUint >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetStateUintRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetStateUintRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetStateUint >
template<>
struct DataType< ::mujoco_ros_msgs::GetStateUintRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetStateUint >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetStateUintRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::GetStateUintResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::GetStateUint >
template<>
struct MD5Sum< ::mujoco_ros_msgs::GetStateUintResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::GetStateUint >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetStateUintResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::GetStateUintResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::GetStateUint >
template<>
struct DataType< ::mujoco_ros_msgs::GetStateUintResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::GetStateUint >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::GetStateUintResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETSTATEUINT_H
