// Generated by gencpp from file mujoco_ros_msgs/GetSimInfoResponse.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_GETSIMINFORESPONSE_H
#define MUJOCO_ROS_MSGS_MESSAGE_GETSIMINFORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mujoco_ros_msgs/SimInfo.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct GetSimInfoResponse_
{
  typedef GetSimInfoResponse_<ContainerAllocator> Type;

  GetSimInfoResponse_()
    : state()  {
    }
  GetSimInfoResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mujoco_ros_msgs::SimInfo_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSimInfoResponse_

typedef ::mujoco_ros_msgs::GetSimInfoResponse_<std::allocator<void> > GetSimInfoResponse;

typedef boost::shared_ptr< ::mujoco_ros_msgs::GetSimInfoResponse > GetSimInfoResponsePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::GetSimInfoResponse const> GetSimInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d1bcf43ea2e10aaf5f5745e953cd88d";
  }

  static const char* value(const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d1bcf43ea2e10aaULL;
  static const uint64_t static_value2 = 0xf5f5745e953cd88dULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/GetSimInfoResponse";
  }

  static const char* value(const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/SimInfo state\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/SimInfo\n"
"string model_path\n"
"bool model_valid\n"
"uint16 load_count # counter of (re)loads\n"
"mujoco_ros_msgs/StateUint loading_state\n"
"bool paused\n"
"uint16 pending_sim_steps\n"
"float32 rt_measured # measured real-time factor\n"
"float32 rt_setting # desired real-time factor\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/StateUint\n"
"uint8 value\n"
"string description\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSimInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::GetSimInfoResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_GETSIMINFORESPONSE_H
