// Generated by gencpp from file mujoco_ros_msgs/MocapState.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_MOCAPSTATE_H
#define MUJOCO_ROS_MSGS_MESSAGE_MOCAPSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct MocapState_
{
  typedef MocapState_<ContainerAllocator> Type;

  MocapState_()
    : name()
    , pose()  {
    }
  MocapState_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> const> ConstPtr;

}; // struct MocapState_

typedef ::mujoco_ros_msgs::MocapState_<std::allocator<void> > MocapState;

typedef boost::shared_ptr< ::mujoco_ros_msgs::MocapState > MocapStatePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::MocapState const> MocapStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::MocapState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::MocapState_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::MocapState_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::MocapState_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::MocapState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "045635c3584f517d80705c4000be320f";
  }

  static const char* value(const ::mujoco_ros_msgs::MocapState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x045635c3584f517dULL;
  static const uint64_t static_value2 = 0x80705c4000be320fULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/MocapState";
  }

  static const char* value(const ::mujoco_ros_msgs::MocapState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name\n"
"geometry_msgs/PoseStamped[] pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::MocapState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MocapState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::MocapState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    if (v.name.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.name[i]);
    }
    if (v.name.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    if (v.pose.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.pose[i]);
    }
    if (v.pose.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_MOCAPSTATE_H
