// Generated by gencpp from file mujoco_ros_msgs/PluginStats.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_PLUGINSTATS_H
#define MUJOCO_ROS_MSGS_MESSAGE_PLUGINSTATS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct PluginStats_
{
  typedef PluginStats_<ContainerAllocator> Type;

  PluginStats_()
    : plugin_type()
    , load_time(0.0)
    , reset_time(0.0)
    , ema_steptime_control(0.0)
    , ema_steptime_passive(0.0)
    , ema_steptime_render(0.0)
    , ema_steptime_last_stage(0.0)  {
    }
  PluginStats_(const ContainerAllocator& _alloc)
    : plugin_type(_alloc)
    , load_time(0.0)
    , reset_time(0.0)
    , ema_steptime_control(0.0)
    , ema_steptime_passive(0.0)
    , ema_steptime_render(0.0)
    , ema_steptime_last_stage(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _plugin_type_type;
  _plugin_type_type plugin_type;

   typedef float _load_time_type;
  _load_time_type load_time;

   typedef float _reset_time_type;
  _reset_time_type reset_time;

   typedef float _ema_steptime_control_type;
  _ema_steptime_control_type ema_steptime_control;

   typedef float _ema_steptime_passive_type;
  _ema_steptime_passive_type ema_steptime_passive;

   typedef float _ema_steptime_render_type;
  _ema_steptime_render_type ema_steptime_render;

   typedef float _ema_steptime_last_stage_type;
  _ema_steptime_last_stage_type ema_steptime_last_stage;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> const> ConstPtr;

}; // struct PluginStats_

typedef ::mujoco_ros_msgs::PluginStats_<std::allocator<void> > PluginStats;

typedef boost::shared_ptr< ::mujoco_ros_msgs::PluginStats > PluginStatsPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::PluginStats const> PluginStatsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator2> & rhs)
{
  return lhs.plugin_type == rhs.plugin_type &&
    lhs.load_time == rhs.load_time &&
    lhs.reset_time == rhs.reset_time &&
    lhs.ema_steptime_control == rhs.ema_steptime_control &&
    lhs.ema_steptime_passive == rhs.ema_steptime_passive &&
    lhs.ema_steptime_render == rhs.ema_steptime_render &&
    lhs.ema_steptime_last_stage == rhs.ema_steptime_last_stage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8952a8d56593bd9d53888ef079c075b0";
  }

  static const char* value(const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8952a8d56593bd9dULL;
  static const uint64_t static_value2 = 0x53888ef079c075b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/PluginStats";
  }

  static const char* value(const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string plugin_type\n"
"float32 load_time\n"
"float32 reset_time\n"
"float32 ema_steptime_control\n"
"float32 ema_steptime_passive\n"
"float32 ema_steptime_render\n"
"float32 ema_steptime_last_stage\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plugin_type);
      stream.next(m.load_time);
      stream.next(m.reset_time);
      stream.next(m.ema_steptime_control);
      stream.next(m.ema_steptime_passive);
      stream.next(m.ema_steptime_render);
      stream.next(m.ema_steptime_last_stage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PluginStats_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::PluginStats_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::PluginStats_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "plugin_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.plugin_type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "load_time: ";
    Printer<float>::stream(s, indent + "  ", v.load_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reset_time: ";
    Printer<float>::stream(s, indent + "  ", v.reset_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ema_steptime_control: ";
    Printer<float>::stream(s, indent + "  ", v.ema_steptime_control);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ema_steptime_passive: ";
    Printer<float>::stream(s, indent + "  ", v.ema_steptime_passive);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ema_steptime_render: ";
    Printer<float>::stream(s, indent + "  ", v.ema_steptime_render);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ema_steptime_last_stage: ";
    Printer<float>::stream(s, indent + "  ", v.ema_steptime_last_stage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_PLUGINSTATS_H
