// Generated by gencpp from file mujoco_ros_msgs/RegisterSensorNoiseModelsResponse.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_REGISTERSENSORNOISEMODELSRESPONSE_H
#define MUJOCO_ROS_MSGS_MESSAGE_REGISTERSENSORNOISEMODELSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct RegisterSensorNoiseModelsResponse_
{
  typedef RegisterSensorNoiseModelsResponse_<ContainerAllocator> Type;

  RegisterSensorNoiseModelsResponse_()
    : success(false)  {
    }
  RegisterSensorNoiseModelsResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterSensorNoiseModelsResponse_

typedef ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<std::allocator<void> > RegisterSensorNoiseModelsResponse;

typedef boost::shared_ptr< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse > RegisterSensorNoiseModelsResponsePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse const> RegisterSensorNoiseModelsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/RegisterSensorNoiseModelsResponse";
  }

  static const char* value(const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterSensorNoiseModelsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::RegisterSensorNoiseModelsResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_REGISTERSENSORNOISEMODELSRESPONSE_H
