// Generated by gencpp from file mujoco_ros_msgs/ReloadRequest.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_RELOADREQUEST_H
#define MUJOCO_ROS_MSGS_MESSAGE_RELOADREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct ReloadRequest_
{
  typedef ReloadRequest_<ContainerAllocator> Type;

  ReloadRequest_()
    : model()
    , admin_hash()  {
    }
  ReloadRequest_(const ContainerAllocator& _alloc)
    : model(_alloc)
    , admin_hash(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_type;
  _model_type model;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _admin_hash_type;
  _admin_hash_type admin_hash;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReloadRequest_

typedef ::mujoco_ros_msgs::ReloadRequest_<std::allocator<void> > ReloadRequest;

typedef boost::shared_ptr< ::mujoco_ros_msgs::ReloadRequest > ReloadRequestPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::ReloadRequest const> ReloadRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator2> & rhs)
{
  return lhs.model == rhs.model &&
    lhs.admin_hash == rhs.admin_hash;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1f217467c32516ee5d12949448679ea";
  }

  static const char* value(const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1f217467c32516eULL;
  static const uint64_t static_value2 = 0xe5d12949448679eaULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/ReloadRequest";
  }

  static const char* value(const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model\n"
"string admin_hash\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model);
      stream.next(m.admin_hash);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReloadRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::ReloadRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "admin_hash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.admin_hash);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_RELOADREQUEST_H
