// Generated by gencpp from file mujoco_ros_msgs/ResetBodyQPos.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_RESETBODYQPOS_H
#define MUJOCO_ROS_MSGS_MESSAGE_RESETBODYQPOS_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/ResetBodyQPosRequest.h>
#include <mujoco_ros_msgs/ResetBodyQPosResponse.h>


namespace mujoco_ros_msgs
{

struct ResetBodyQPos
{

typedef ResetBodyQPosRequest Request;
typedef ResetBodyQPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetBodyQPos
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::ResetBodyQPos > {
  static const char* value()
  {
    return "a5102c837d3e894714b27aecbae54380";
  }

  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPos&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::ResetBodyQPos > {
  static const char* value()
  {
    return "mujoco_ros_msgs/ResetBodyQPos";
  }

  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPos&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::ResetBodyQPosRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::ResetBodyQPos >
template<>
struct MD5Sum< ::mujoco_ros_msgs::ResetBodyQPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::ResetBodyQPos >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::ResetBodyQPosRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::ResetBodyQPos >
template<>
struct DataType< ::mujoco_ros_msgs::ResetBodyQPosRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::ResetBodyQPos >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::ResetBodyQPosResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::ResetBodyQPos >
template<>
struct MD5Sum< ::mujoco_ros_msgs::ResetBodyQPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::ResetBodyQPos >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::ResetBodyQPosResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::ResetBodyQPos >
template<>
struct DataType< ::mujoco_ros_msgs::ResetBodyQPosResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::ResetBodyQPos >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_RESETBODYQPOS_H
