// Generated by gencpp from file mujoco_ros_msgs/ResetBodyQPosRequest.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_RESETBODYQPOSREQUEST_H
#define MUJOCO_ROS_MSGS_MESSAGE_RESETBODYQPOSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct ResetBodyQPosRequest_
{
  typedef ResetBodyQPosRequest_<ContainerAllocator> Type;

  ResetBodyQPosRequest_()
    : name()
    , admin_hash()  {
    }
  ResetBodyQPosRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , admin_hash(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _admin_hash_type;
  _admin_hash_type admin_hash;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetBodyQPosRequest_

typedef ::mujoco_ros_msgs::ResetBodyQPosRequest_<std::allocator<void> > ResetBodyQPosRequest;

typedef boost::shared_ptr< ::mujoco_ros_msgs::ResetBodyQPosRequest > ResetBodyQPosRequestPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::ResetBodyQPosRequest const> ResetBodyQPosRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.admin_hash == rhs.admin_hash;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97071bee6aa31964d35a900defe051e2";
  }

  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97071bee6aa31964ULL;
  static const uint64_t static_value2 = 0xd35a900defe051e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/ResetBodyQPosRequest";
  }

  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string admin_hash\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.admin_hash);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetBodyQPosRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::ResetBodyQPosRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "admin_hash: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.admin_hash);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_RESETBODYQPOSREQUEST_H
