// Generated by gencpp from file mujoco_ros_msgs/SetBodyState.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETBODYSTATE_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETBODYSTATE_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/SetBodyStateRequest.h>
#include <mujoco_ros_msgs/SetBodyStateResponse.h>


namespace mujoco_ros_msgs
{

struct SetBodyState
{

typedef SetBodyStateRequest Request;
typedef SetBodyStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBodyState
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::SetBodyState > {
  static const char* value()
  {
    return "dca3e244d1ac24ae8650b204afd0c666";
  }

  static const char* value(const ::mujoco_ros_msgs::SetBodyState&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::SetBodyState > {
  static const char* value()
  {
    return "mujoco_ros_msgs/SetBodyState";
  }

  static const char* value(const ::mujoco_ros_msgs::SetBodyState&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::SetBodyStateRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetBodyState >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetBodyStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetBodyStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetBodyStateRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetBodyState >
template<>
struct DataType< ::mujoco_ros_msgs::SetBodyStateRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetBodyStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::SetBodyStateResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetBodyState >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetBodyStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetBodyStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetBodyStateResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetBodyState >
template<>
struct DataType< ::mujoco_ros_msgs::SetBodyStateResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetBodyState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetBodyStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETBODYSTATE_H
