// Generated by gencpp from file mujoco_ros_msgs/SetEqualityConstraintParametersResponse.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETEQUALITYCONSTRAINTPARAMETERSRESPONSE_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETEQUALITYCONSTRAINTPARAMETERSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct SetEqualityConstraintParametersResponse_
{
  typedef SetEqualityConstraintParametersResponse_<ContainerAllocator> Type;

  SetEqualityConstraintParametersResponse_()
    : success(false)
    , status_message()  {
    }
  SetEqualityConstraintParametersResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , status_message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetEqualityConstraintParametersResponse_

typedef ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<std::allocator<void> > SetEqualityConstraintParametersResponse;

typedef boost::shared_ptr< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse > SetEqualityConstraintParametersResponsePtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse const> SetEqualityConstraintParametersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ec6f3eff0161f4257b808b12bc830c2";
  }

  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ec6f3eff0161f42ULL;
  static const uint64_t static_value2 = 0x57b808b12bc830c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/SetEqualityConstraintParametersResponse";
  }

  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string status_message\n"
"\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.status_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEqualityConstraintParametersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETEQUALITYCONSTRAINTPARAMETERSRESPONSE_H
