// Generated by gencpp from file mujoco_ros_msgs/SetEqualityConstraintParameters.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETEQUALITYCONSTRAINTPARAMETERS_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETEQUALITYCONSTRAINTPARAMETERS_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/SetEqualityConstraintParametersRequest.h>
#include <mujoco_ros_msgs/SetEqualityConstraintParametersResponse.h>


namespace mujoco_ros_msgs
{

struct SetEqualityConstraintParameters
{

typedef SetEqualityConstraintParametersRequest Request;
typedef SetEqualityConstraintParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEqualityConstraintParameters
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParameters > {
  static const char* value()
  {
    return "8c7bc419b78113b1ae9c6f7fe138068f";
  }

  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParameters&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::SetEqualityConstraintParameters > {
  static const char* value()
  {
    return "mujoco_ros_msgs/SetEqualityConstraintParameters";
  }

  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParameters&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParametersRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParameters >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetEqualityConstraintParametersRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetEqualityConstraintParameters >
template<>
struct DataType< ::mujoco_ros_msgs::SetEqualityConstraintParametersRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParameters >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetEqualityConstraintParameters >
template<>
struct DataType< ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetEqualityConstraintParameters >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetEqualityConstraintParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETEQUALITYCONSTRAINTPARAMETERS_H
