// Generated by gencpp from file mujoco_ros_msgs/SetGeomProperties.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETGEOMPROPERTIES_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETGEOMPROPERTIES_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/SetGeomPropertiesRequest.h>
#include <mujoco_ros_msgs/SetGeomPropertiesResponse.h>


namespace mujoco_ros_msgs
{

struct SetGeomProperties
{

typedef SetGeomPropertiesRequest Request;
typedef SetGeomPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGeomProperties
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::SetGeomProperties > {
  static const char* value()
  {
    return "a7072e8bafa01bef541263a9142aa174";
  }

  static const char* value(const ::mujoco_ros_msgs::SetGeomProperties&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::SetGeomProperties > {
  static const char* value()
  {
    return "mujoco_ros_msgs/SetGeomProperties";
  }

  static const char* value(const ::mujoco_ros_msgs::SetGeomProperties&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::SetGeomPropertiesRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetGeomProperties >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetGeomPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetGeomProperties >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetGeomPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetGeomPropertiesRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetGeomProperties >
template<>
struct DataType< ::mujoco_ros_msgs::SetGeomPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetGeomProperties >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetGeomPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::SetGeomPropertiesResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetGeomProperties >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetGeomPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetGeomProperties >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetGeomPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetGeomPropertiesResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetGeomProperties >
template<>
struct DataType< ::mujoco_ros_msgs::SetGeomPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetGeomProperties >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetGeomPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETGEOMPROPERTIES_H
