// Generated by gencpp from file mujoco_ros_msgs/SetMocapStateRequest.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETMOCAPSTATEREQUEST_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETMOCAPSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mujoco_ros_msgs/MocapState.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct SetMocapStateRequest_
{
  typedef SetMocapStateRequest_<ContainerAllocator> Type;

  SetMocapStateRequest_()
    : mocap_state()  {
    }
  SetMocapStateRequest_(const ContainerAllocator& _alloc)
    : mocap_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mujoco_ros_msgs::MocapState_<ContainerAllocator>  _mocap_state_type;
  _mocap_state_type mocap_state;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetMocapStateRequest_

typedef ::mujoco_ros_msgs::SetMocapStateRequest_<std::allocator<void> > SetMocapStateRequest;

typedef boost::shared_ptr< ::mujoco_ros_msgs::SetMocapStateRequest > SetMocapStateRequestPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::SetMocapStateRequest const> SetMocapStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mocap_state == rhs.mocap_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57d6efb59fd3515a1a8e17a05c1b1a3f";
  }

  static const char* value(const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57d6efb59fd3515aULL;
  static const uint64_t static_value2 = 0x1a8e17a05c1b1a3fULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/SetMocapStateRequest";
  }

  static const char* value(const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/MocapState mocap_state\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/MocapState\n"
"string[] name\n"
"geometry_msgs/PoseStamped[] pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mocap_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMocapStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::SetMocapStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mocap_state: ";
    Printer< ::mujoco_ros_msgs::MocapState_<ContainerAllocator> >::stream(s, indent + "  ", v.mocap_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETMOCAPSTATEREQUEST_H
