// Generated by gencpp from file mujoco_ros_msgs/SetMocapState.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETMOCAPSTATE_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETMOCAPSTATE_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/SetMocapStateRequest.h>
#include <mujoco_ros_msgs/SetMocapStateResponse.h>


namespace mujoco_ros_msgs
{

struct SetMocapState
{

typedef SetMocapStateRequest Request;
typedef SetMocapStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMocapState
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::SetMocapState > {
  static const char* value()
  {
    return "59922d272c5d8f5030a19521538c2732";
  }

  static const char* value(const ::mujoco_ros_msgs::SetMocapState&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::SetMocapState > {
  static const char* value()
  {
    return "mujoco_ros_msgs/SetMocapState";
  }

  static const char* value(const ::mujoco_ros_msgs::SetMocapState&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::SetMocapStateRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetMocapState >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetMocapStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetMocapState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetMocapStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetMocapStateRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetMocapState >
template<>
struct DataType< ::mujoco_ros_msgs::SetMocapStateRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetMocapState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetMocapStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::SetMocapStateResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetMocapState >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetMocapStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetMocapState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetMocapStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetMocapStateResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetMocapState >
template<>
struct DataType< ::mujoco_ros_msgs::SetMocapStateResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetMocapState >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetMocapStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETMOCAPSTATE_H
