// Generated by gencpp from file mujoco_ros_msgs/SetPause.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SETPAUSE_H
#define MUJOCO_ROS_MSGS_MESSAGE_SETPAUSE_H

#include <ros/service_traits.h>


#include <mujoco_ros_msgs/SetPauseRequest.h>
#include <mujoco_ros_msgs/SetPauseResponse.h>


namespace mujoco_ros_msgs
{

struct SetPause
{

typedef SetPauseRequest Request;
typedef SetPauseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPause
} // namespace mujoco_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mujoco_ros_msgs::SetPause > {
  static const char* value()
  {
    return "b3b6340c1a873657e7d239a0abbde573";
  }

  static const char* value(const ::mujoco_ros_msgs::SetPause&) { return value(); }
};

template<>
struct DataType< ::mujoco_ros_msgs::SetPause > {
  static const char* value()
  {
    return "mujoco_ros_msgs/SetPause";
  }

  static const char* value(const ::mujoco_ros_msgs::SetPause&) { return value(); }
};


// service_traits::MD5Sum< ::mujoco_ros_msgs::SetPauseRequest> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetPause >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetPauseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetPause >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetPauseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetPauseRequest> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetPause >
template<>
struct DataType< ::mujoco_ros_msgs::SetPauseRequest>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetPause >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetPauseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mujoco_ros_msgs::SetPauseResponse> should match
// service_traits::MD5Sum< ::mujoco_ros_msgs::SetPause >
template<>
struct MD5Sum< ::mujoco_ros_msgs::SetPauseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mujoco_ros_msgs::SetPause >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetPauseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mujoco_ros_msgs::SetPauseResponse> should match
// service_traits::DataType< ::mujoco_ros_msgs::SetPause >
template<>
struct DataType< ::mujoco_ros_msgs::SetPauseResponse>
{
  static const char* value()
  {
    return DataType< ::mujoco_ros_msgs::SetPause >::value();
  }
  static const char* value(const ::mujoco_ros_msgs::SetPauseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SETPAUSE_H
