// Generated by gencpp from file mujoco_ros_msgs/SimInfo.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_SIMINFO_H
#define MUJOCO_ROS_MSGS_MESSAGE_SIMINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mujoco_ros_msgs/StateUint.h>

namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct SimInfo_
{
  typedef SimInfo_<ContainerAllocator> Type;

  SimInfo_()
    : model_path()
    , model_valid(false)
    , load_count(0)
    , loading_state()
    , paused(false)
    , pending_sim_steps(0)
    , rt_measured(0.0)
    , rt_setting(0.0)  {
    }
  SimInfo_(const ContainerAllocator& _alloc)
    : model_path(_alloc)
    , model_valid(false)
    , load_count(0)
    , loading_state(_alloc)
    , paused(false)
    , pending_sim_steps(0)
    , rt_measured(0.0)
    , rt_setting(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _model_path_type;
  _model_path_type model_path;

   typedef uint8_t _model_valid_type;
  _model_valid_type model_valid;

   typedef uint16_t _load_count_type;
  _load_count_type load_count;

   typedef  ::mujoco_ros_msgs::StateUint_<ContainerAllocator>  _loading_state_type;
  _loading_state_type loading_state;

   typedef uint8_t _paused_type;
  _paused_type paused;

   typedef uint16_t _pending_sim_steps_type;
  _pending_sim_steps_type pending_sim_steps;

   typedef float _rt_measured_type;
  _rt_measured_type rt_measured;

   typedef float _rt_setting_type;
  _rt_setting_type rt_setting;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> const> ConstPtr;

}; // struct SimInfo_

typedef ::mujoco_ros_msgs::SimInfo_<std::allocator<void> > SimInfo;

typedef boost::shared_ptr< ::mujoco_ros_msgs::SimInfo > SimInfoPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::SimInfo const> SimInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator2> & rhs)
{
  return lhs.model_path == rhs.model_path &&
    lhs.model_valid == rhs.model_valid &&
    lhs.load_count == rhs.load_count &&
    lhs.loading_state == rhs.loading_state &&
    lhs.paused == rhs.paused &&
    lhs.pending_sim_steps == rhs.pending_sim_steps &&
    lhs.rt_measured == rhs.rt_measured &&
    lhs.rt_setting == rhs.rt_setting;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50fb0bcacffb362708f3fc623e7e9a63";
  }

  static const char* value(const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50fb0bcacffb3627ULL;
  static const uint64_t static_value2 = 0x08f3fc623e7e9a63ULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/SimInfo";
  }

  static const char* value(const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_path\n"
"bool model_valid\n"
"uint16 load_count # counter of (re)loads\n"
"mujoco_ros_msgs/StateUint loading_state\n"
"bool paused\n"
"uint16 pending_sim_steps\n"
"float32 rt_measured # measured real-time factor\n"
"float32 rt_setting # desired real-time factor\n"
"\n"
"================================================================================\n"
"MSG: mujoco_ros_msgs/StateUint\n"
"uint8 value\n"
"string description\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_path);
      stream.next(m.model_valid);
      stream.next(m.load_count);
      stream.next(m.loading_state);
      stream.next(m.paused);
      stream.next(m.pending_sim_steps);
      stream.next(m.rt_measured);
      stream.next(m.rt_setting);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::SimInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::SimInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "model_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.model_path);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "model_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.model_valid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "load_count: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.load_count);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "loading_state: ";
    Printer< ::mujoco_ros_msgs::StateUint_<ContainerAllocator> >::stream(s, indent + "  ", v.loading_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "paused: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.paused);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pending_sim_steps: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pending_sim_steps);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rt_measured: ";
    Printer<float>::stream(s, indent + "  ", v.rt_measured);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rt_setting: ";
    Printer<float>::stream(s, indent + "  ", v.rt_setting);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_SIMINFO_H
