// Generated by gencpp from file mujoco_ros_msgs/StepGoal.msg
// DO NOT EDIT!


#ifndef MUJOCO_ROS_MSGS_MESSAGE_STEPGOAL_H
#define MUJOCO_ROS_MSGS_MESSAGE_STEPGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mujoco_ros_msgs
{
template <class ContainerAllocator>
struct StepGoal_
{
  typedef StepGoal_<ContainerAllocator> Type;

  StepGoal_()
    : num_steps(0)  {
    }
  StepGoal_(const ContainerAllocator& _alloc)
    : num_steps(0)  {
  (void)_alloc;
    }



   typedef uint16_t _num_steps_type;
  _num_steps_type num_steps;





  typedef boost::shared_ptr< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StepGoal_

typedef ::mujoco_ros_msgs::StepGoal_<std::allocator<void> > StepGoal;

typedef boost::shared_ptr< ::mujoco_ros_msgs::StepGoal > StepGoalPtr;
typedef boost::shared_ptr< ::mujoco_ros_msgs::StepGoal const> StepGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num_steps == rhs.num_steps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator1> & lhs, const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mujoco_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "225dddb47d0d74321c7417323fd734df";
  }

  static const char* value(const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x225dddb47d0d7432ULL;
  static const uint64_t static_value2 = 0x1c7417323fd734dfULL;
};

template<class ContainerAllocator>
struct DataType< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mujoco_ros_msgs/StepGoal";
  }

  static const char* value(const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint16 num_steps\n"
;
  }

  static const char* value(const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_steps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mujoco_ros_msgs::StepGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mujoco_ros_msgs::StepGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "num_steps: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.num_steps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUJOCO_ROS_MSGS_MESSAGE_STEPGOAL_H
