# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mujoco_ros_msgs/EqualityConstraintParameters.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import mujoco_ros_msgs.msg

class EqualityConstraintParameters(genpy.Message):
  _md5sum = "152c371cf6b748601a865ee2d968aec7"
  _type = "mujoco_ros_msgs/EqualityConstraintParameters"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string name
mujoco_ros_msgs/EqualityConstraintType type
mujoco_ros_msgs/SolverParameters solverParameters
bool active
string classParam
string element1
string element2
float64 torquescale
geometry_msgs/Vector3 anchor
geometry_msgs/Pose relpose
float64[] polycoef

================================================================================
MSG: mujoco_ros_msgs/EqualityConstraintType
uint16 value
uint16 CONNECT=0
uint16 WELD=1
uint16 JOINT=2
uint16 TENDON=3

================================================================================
MSG: mujoco_ros_msgs/SolverParameters
# solimp parameters

float64 dmin
float64 dmax
float64 width
float64 midpoint
float64 power

# solref parameters

float64 timeconst
float64 dampratio

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['name','type','solverParameters','active','classParam','element1','element2','torquescale','anchor','relpose','polycoef']
  _slot_types = ['string','mujoco_ros_msgs/EqualityConstraintType','mujoco_ros_msgs/SolverParameters','bool','string','string','string','float64','geometry_msgs/Vector3','geometry_msgs/Pose','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,type,solverParameters,active,classParam,element1,element2,torquescale,anchor,relpose,polycoef

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EqualityConstraintParameters, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.type is None:
        self.type = mujoco_ros_msgs.msg.EqualityConstraintType()
      if self.solverParameters is None:
        self.solverParameters = mujoco_ros_msgs.msg.SolverParameters()
      if self.active is None:
        self.active = False
      if self.classParam is None:
        self.classParam = ''
      if self.element1 is None:
        self.element1 = ''
      if self.element2 is None:
        self.element2 = ''
      if self.torquescale is None:
        self.torquescale = 0.
      if self.anchor is None:
        self.anchor = geometry_msgs.msg.Vector3()
      if self.relpose is None:
        self.relpose = geometry_msgs.msg.Pose()
      if self.polycoef is None:
        self.polycoef = []
    else:
      self.name = ''
      self.type = mujoco_ros_msgs.msg.EqualityConstraintType()
      self.solverParameters = mujoco_ros_msgs.msg.SolverParameters()
      self.active = False
      self.classParam = ''
      self.element1 = ''
      self.element2 = ''
      self.torquescale = 0.
      self.anchor = geometry_msgs.msg.Vector3()
      self.relpose = geometry_msgs.msg.Pose()
      self.polycoef = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H7dB().pack(_x.type.value, _x.solverParameters.dmin, _x.solverParameters.dmax, _x.solverParameters.width, _x.solverParameters.midpoint, _x.solverParameters.power, _x.solverParameters.timeconst, _x.solverParameters.dampratio, _x.active))
      _x = self.classParam
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.element1
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.element2
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d().pack(_x.torquescale, _x.anchor.x, _x.anchor.y, _x.anchor.z, _x.relpose.position.x, _x.relpose.position.y, _x.relpose.position.z, _x.relpose.orientation.x, _x.relpose.orientation.y, _x.relpose.orientation.z, _x.relpose.orientation.w))
      length = len(self.polycoef)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.polycoef))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.type is None:
        self.type = mujoco_ros_msgs.msg.EqualityConstraintType()
      if self.solverParameters is None:
        self.solverParameters = mujoco_ros_msgs.msg.SolverParameters()
      if self.anchor is None:
        self.anchor = geometry_msgs.msg.Vector3()
      if self.relpose is None:
        self.relpose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.type.value, _x.solverParameters.dmin, _x.solverParameters.dmax, _x.solverParameters.width, _x.solverParameters.midpoint, _x.solverParameters.power, _x.solverParameters.timeconst, _x.solverParameters.dampratio, _x.active,) = _get_struct_H7dB().unpack(str[start:end])
      self.active = bool(self.active)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.classParam = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.classParam = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.element1 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.element1 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.element2 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.element2 = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.torquescale, _x.anchor.x, _x.anchor.y, _x.anchor.z, _x.relpose.position.x, _x.relpose.position.y, _x.relpose.position.z, _x.relpose.orientation.x, _x.relpose.orientation.y, _x.relpose.orientation.z, _x.relpose.orientation.w,) = _get_struct_11d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.polycoef = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_H7dB().pack(_x.type.value, _x.solverParameters.dmin, _x.solverParameters.dmax, _x.solverParameters.width, _x.solverParameters.midpoint, _x.solverParameters.power, _x.solverParameters.timeconst, _x.solverParameters.dampratio, _x.active))
      _x = self.classParam
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.element1
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.element2
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d().pack(_x.torquescale, _x.anchor.x, _x.anchor.y, _x.anchor.z, _x.relpose.position.x, _x.relpose.position.y, _x.relpose.position.z, _x.relpose.orientation.x, _x.relpose.orientation.y, _x.relpose.orientation.z, _x.relpose.orientation.w))
      length = len(self.polycoef)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.polycoef.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.type is None:
        self.type = mujoco_ros_msgs.msg.EqualityConstraintType()
      if self.solverParameters is None:
        self.solverParameters = mujoco_ros_msgs.msg.SolverParameters()
      if self.anchor is None:
        self.anchor = geometry_msgs.msg.Vector3()
      if self.relpose is None:
        self.relpose = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 59
      (_x.type.value, _x.solverParameters.dmin, _x.solverParameters.dmax, _x.solverParameters.width, _x.solverParameters.midpoint, _x.solverParameters.power, _x.solverParameters.timeconst, _x.solverParameters.dampratio, _x.active,) = _get_struct_H7dB().unpack(str[start:end])
      self.active = bool(self.active)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.classParam = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.classParam = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.element1 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.element1 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.element2 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.element2 = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.torquescale, _x.anchor.x, _x.anchor.y, _x.anchor.z, _x.relpose.position.x, _x.relpose.position.y, _x.relpose.position.z, _x.relpose.orientation.x, _x.relpose.orientation.y, _x.relpose.orientation.z, _x.relpose.orientation.w,) = _get_struct_11d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.polycoef = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11d = None
def _get_struct_11d():
    global _struct_11d
    if _struct_11d is None:
        _struct_11d = struct.Struct("<11d")
    return _struct_11d
_struct_H7dB = None
def _get_struct_H7dB():
    global _struct_H7dB
    if _struct_H7dB is None:
        _struct_H7dB = struct.Struct("<H7dB")
    return _struct_H7dB
