# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mujoco_ros_msgs/SolverParameters.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SolverParameters(genpy.Message):
  _md5sum = "5b04c6e904f30629555e3a6f113fc0eb"
  _type = "mujoco_ros_msgs/SolverParameters"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# solimp parameters

float64 dmin
float64 dmax
float64 width
float64 midpoint
float64 power

# solref parameters

float64 timeconst
float64 dampratio
"""
  __slots__ = ['dmin','dmax','width','midpoint','power','timeconst','dampratio']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dmin,dmax,width,midpoint,power,timeconst,dampratio

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SolverParameters, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.dmin is None:
        self.dmin = 0.
      if self.dmax is None:
        self.dmax = 0.
      if self.width is None:
        self.width = 0.
      if self.midpoint is None:
        self.midpoint = 0.
      if self.power is None:
        self.power = 0.
      if self.timeconst is None:
        self.timeconst = 0.
      if self.dampratio is None:
        self.dampratio = 0.
    else:
      self.dmin = 0.
      self.dmax = 0.
      self.width = 0.
      self.midpoint = 0.
      self.power = 0.
      self.timeconst = 0.
      self.dampratio = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.dmin, _x.dmax, _x.width, _x.midpoint, _x.power, _x.timeconst, _x.dampratio))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.dmin, _x.dmax, _x.width, _x.midpoint, _x.power, _x.timeconst, _x.dampratio,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.dmin, _x.dmax, _x.width, _x.midpoint, _x.power, _x.timeconst, _x.dampratio))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.dmin, _x.dmax, _x.width, _x.midpoint, _x.power, _x.timeconst, _x.dampratio,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
