# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bimanual_drinking_v5_msgs/SystemState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class SystemState(genpy.Message):
  _md5sum = "7092e774a948ee80cb8059d5afed3515"
  _type = "bimanual_drinking_v5_msgs/SystemState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
string phase
bool busy
bool estop
bool moveit_ready
bool bottle_attached
bool left_hand_alive
bool right_hand_alive
bool left_hand_settled
bool right_hand_settled
string last_error

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','phase','busy','estop','moveit_ready','bottle_attached','left_hand_alive','right_hand_alive','left_hand_settled','right_hand_settled','last_error']
  _slot_types = ['std_msgs/Header','string','bool','bool','bool','bool','bool','bool','bool','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,phase,busy,estop,moveit_ready,bottle_attached,left_hand_alive,right_hand_alive,left_hand_settled,right_hand_settled,last_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SystemState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.phase is None:
        self.phase = ''
      if self.busy is None:
        self.busy = False
      if self.estop is None:
        self.estop = False
      if self.moveit_ready is None:
        self.moveit_ready = False
      if self.bottle_attached is None:
        self.bottle_attached = False
      if self.left_hand_alive is None:
        self.left_hand_alive = False
      if self.right_hand_alive is None:
        self.right_hand_alive = False
      if self.left_hand_settled is None:
        self.left_hand_settled = False
      if self.right_hand_settled is None:
        self.right_hand_settled = False
      if self.last_error is None:
        self.last_error = ''
    else:
      self.header = std_msgs.msg.Header()
      self.phase = ''
      self.busy = False
      self.estop = False
      self.moveit_ready = False
      self.bottle_attached = False
      self.left_hand_alive = False
      self.right_hand_alive = False
      self.left_hand_settled = False
      self.right_hand_settled = False
      self.last_error = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.phase
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.busy, _x.estop, _x.moveit_ready, _x.bottle_attached, _x.left_hand_alive, _x.right_hand_alive, _x.left_hand_settled, _x.right_hand_settled))
      _x = self.last_error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.phase = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.phase = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.busy, _x.estop, _x.moveit_ready, _x.bottle_attached, _x.left_hand_alive, _x.right_hand_alive, _x.left_hand_settled, _x.right_hand_settled,) = _get_struct_8B().unpack(str[start:end])
      self.busy = bool(self.busy)
      self.estop = bool(self.estop)
      self.moveit_ready = bool(self.moveit_ready)
      self.bottle_attached = bool(self.bottle_attached)
      self.left_hand_alive = bool(self.left_hand_alive)
      self.right_hand_alive = bool(self.right_hand_alive)
      self.left_hand_settled = bool(self.left_hand_settled)
      self.right_hand_settled = bool(self.right_hand_settled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_error = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.phase
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.busy, _x.estop, _x.moveit_ready, _x.bottle_attached, _x.left_hand_alive, _x.right_hand_alive, _x.left_hand_settled, _x.right_hand_settled))
      _x = self.last_error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.phase = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.phase = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.busy, _x.estop, _x.moveit_ready, _x.bottle_attached, _x.left_hand_alive, _x.right_hand_alive, _x.left_hand_settled, _x.right_hand_settled,) = _get_struct_8B().unpack(str[start:end])
      self.busy = bool(self.busy)
      self.estop = bool(self.estop)
      self.moveit_ready = bool(self.moveit_ready)
      self.bottle_attached = bool(self.bottle_attached)
      self.left_hand_alive = bool(self.left_hand_alive)
      self.right_hand_alive = bool(self.right_hand_alive)
      self.left_hand_settled = bool(self.left_hand_settled)
      self.right_hand_settled = bool(self.right_hand_settled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_error = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
