# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bimanual_drinking_v5_msgs/TaskCommand.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class TaskCommand(genpy.Message):
  _md5sum = "f9e74ce5044da031d687036e93905cdb"
  _type = "bimanual_drinking_v5_msgs/TaskCommand"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """uint8 STATUS=0
uint8 STOP=1
uint8 CLEAR_ESTOP=2
uint8 HOME_HANDS=3
uint8 RUN_BOTTLE_CAP_SEQUENCE=10
uint8 MOVE_LEFT_PREGRASP=20
uint8 GRASP_BOTTLE=21
uint8 MOVE_RIGHT_PREGRASP=30
uint8 GRASP_CAP=31
uint8 UNSCREW=32
uint8 RELEASE_CAP=33
uint8 RELEASE_BOTTLE=34
std_msgs/Header header
uint8 command
float32 speed_scale
bool plan_only

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  STATUS = 0
  STOP = 1
  CLEAR_ESTOP = 2
  HOME_HANDS = 3
  RUN_BOTTLE_CAP_SEQUENCE = 10
  MOVE_LEFT_PREGRASP = 20
  GRASP_BOTTLE = 21
  MOVE_RIGHT_PREGRASP = 30
  GRASP_CAP = 31
  UNSCREW = 32
  RELEASE_CAP = 33
  RELEASE_BOTTLE = 34

  __slots__ = ['header','command','speed_scale','plan_only']
  _slot_types = ['std_msgs/Header','uint8','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,command,speed_scale,plan_only

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TaskCommand, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.command is None:
        self.command = 0
      if self.speed_scale is None:
        self.speed_scale = 0.
      if self.plan_only is None:
        self.plan_only = False
    else:
      self.header = std_msgs.msg.Header()
      self.command = 0
      self.speed_scale = 0.
      self.plan_only = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BfB().pack(_x.command, _x.speed_scale, _x.plan_only))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.command, _x.speed_scale, _x.plan_only,) = _get_struct_BfB().unpack(str[start:end])
      self.plan_only = bool(self.plan_only)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BfB().pack(_x.command, _x.speed_scale, _x.plan_only))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.command, _x.speed_scale, _x.plan_only,) = _get_struct_BfB().unpack(str[start:end])
      self.plan_only = bool(self.plan_only)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_BfB = None
def _get_struct_BfB():
    global _struct_BfB
    if _struct_BfB is None:
        _struct_BfB = struct.Struct("<BfB")
    return _struct_BfB
