// Auto-generated. Do not edit!

// (in-package mujoco_ros_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class StepGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.num_steps = null;
    }
    else {
      if (initObj.hasOwnProperty('num_steps')) {
        this.num_steps = initObj.num_steps
      }
      else {
        this.num_steps = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StepGoal
    // Serialize message field [num_steps]
    bufferOffset = _serializer.uint16(obj.num_steps, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StepGoal
    let len;
    let data = new StepGoal(null);
    // Deserialize message field [num_steps]
    data.num_steps = _deserializer.uint16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'mujoco_ros_msgs/StepGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '225dddb47d0d74321c7417323fd734df';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint16 num_steps
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StepGoal(null);
    if (msg.num_steps !== undefined) {
      resolved.num_steps = msg.num_steps;
    }
    else {
      resolved.num_steps = 0
    }

    return resolved;
    }
};

module.exports = StepGoal;
