// Generated by gencpp from file bimanual_drinking_v5_msgs/SystemState.msg
// DO NOT EDIT!


#ifndef BIMANUAL_DRINKING_V5_MSGS_MESSAGE_SYSTEMSTATE_H
#define BIMANUAL_DRINKING_V5_MSGS_MESSAGE_SYSTEMSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bimanual_drinking_v5_msgs
{
template <class ContainerAllocator>
struct SystemState_
{
  typedef SystemState_<ContainerAllocator> Type;

  SystemState_()
    : header()
    , phase()
    , busy(false)
    , estop(false)
    , moveit_ready(false)
    , bottle_attached(false)
    , left_hand_alive(false)
    , right_hand_alive(false)
    , left_hand_settled(false)
    , right_hand_settled(false)
    , last_error()  {
    }
  SystemState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , phase(_alloc)
    , busy(false)
    , estop(false)
    , moveit_ready(false)
    , bottle_attached(false)
    , left_hand_alive(false)
    , right_hand_alive(false)
    , left_hand_settled(false)
    , right_hand_settled(false)
    , last_error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _phase_type;
  _phase_type phase;

   typedef uint8_t _busy_type;
  _busy_type busy;

   typedef uint8_t _estop_type;
  _estop_type estop;

   typedef uint8_t _moveit_ready_type;
  _moveit_ready_type moveit_ready;

   typedef uint8_t _bottle_attached_type;
  _bottle_attached_type bottle_attached;

   typedef uint8_t _left_hand_alive_type;
  _left_hand_alive_type left_hand_alive;

   typedef uint8_t _right_hand_alive_type;
  _right_hand_alive_type right_hand_alive;

   typedef uint8_t _left_hand_settled_type;
  _left_hand_settled_type left_hand_settled;

   typedef uint8_t _right_hand_settled_type;
  _right_hand_settled_type right_hand_settled;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _last_error_type;
  _last_error_type last_error;





  typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> const> ConstPtr;

}; // struct SystemState_

typedef ::bimanual_drinking_v5_msgs::SystemState_<std::allocator<void> > SystemState;

typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::SystemState > SystemStatePtr;
typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::SystemState const> SystemStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator1> & lhs, const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.phase == rhs.phase &&
    lhs.busy == rhs.busy &&
    lhs.estop == rhs.estop &&
    lhs.moveit_ready == rhs.moveit_ready &&
    lhs.bottle_attached == rhs.bottle_attached &&
    lhs.left_hand_alive == rhs.left_hand_alive &&
    lhs.right_hand_alive == rhs.right_hand_alive &&
    lhs.left_hand_settled == rhs.left_hand_settled &&
    lhs.right_hand_settled == rhs.right_hand_settled &&
    lhs.last_error == rhs.last_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator1> & lhs, const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bimanual_drinking_v5_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7092e774a948ee80cb8059d5afed3515";
  }

  static const char* value(const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7092e774a948ee80ULL;
  static const uint64_t static_value2 = 0xcb8059d5afed3515ULL;
};

template<class ContainerAllocator>
struct DataType< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bimanual_drinking_v5_msgs/SystemState";
  }

  static const char* value(const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string phase\n"
"bool busy\n"
"bool estop\n"
"bool moveit_ready\n"
"bool bottle_attached\n"
"bool left_hand_alive\n"
"bool right_hand_alive\n"
"bool left_hand_settled\n"
"bool right_hand_settled\n"
"string last_error\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.phase);
      stream.next(m.busy);
      stream.next(m.estop);
      stream.next(m.moveit_ready);
      stream.next(m.bottle_attached);
      stream.next(m.left_hand_alive);
      stream.next(m.right_hand_alive);
      stream.next(m.left_hand_settled);
      stream.next(m.right_hand_settled);
      stream.next(m.last_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bimanual_drinking_v5_msgs::SystemState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "phase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.phase);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "busy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.busy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.estop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "moveit_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.moveit_ready);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bottle_attached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bottle_attached);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_hand_alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_hand_alive);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_hand_alive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_hand_alive);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_hand_settled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_hand_settled);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_hand_settled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_hand_settled);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "last_error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.last_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIMANUAL_DRINKING_V5_MSGS_MESSAGE_SYSTEMSTATE_H
