// Generated by gencpp from file bimanual_drinking_v5_msgs/TaskCommand.msg
// DO NOT EDIT!


#ifndef BIMANUAL_DRINKING_V5_MSGS_MESSAGE_TASKCOMMAND_H
#define BIMANUAL_DRINKING_V5_MSGS_MESSAGE_TASKCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bimanual_drinking_v5_msgs
{
template <class ContainerAllocator>
struct TaskCommand_
{
  typedef TaskCommand_<ContainerAllocator> Type;

  TaskCommand_()
    : header()
    , command(0)
    , speed_scale(0.0)
    , plan_only(false)  {
    }
  TaskCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(0)
    , speed_scale(0.0)
    , plan_only(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _command_type;
  _command_type command;

   typedef float _speed_scale_type;
  _speed_scale_type speed_scale;

   typedef uint8_t _plan_only_type;
  _plan_only_type plan_only;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATUS)
  #undef STATUS
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(CLEAR_ESTOP)
  #undef CLEAR_ESTOP
#endif
#if defined(_WIN32) && defined(HOME_HANDS)
  #undef HOME_HANDS
#endif
#if defined(_WIN32) && defined(RUN_BOTTLE_CAP_SEQUENCE)
  #undef RUN_BOTTLE_CAP_SEQUENCE
#endif
#if defined(_WIN32) && defined(MOVE_LEFT_PREGRASP)
  #undef MOVE_LEFT_PREGRASP
#endif
#if defined(_WIN32) && defined(GRASP_BOTTLE)
  #undef GRASP_BOTTLE
#endif
#if defined(_WIN32) && defined(MOVE_RIGHT_PREGRASP)
  #undef MOVE_RIGHT_PREGRASP
#endif
#if defined(_WIN32) && defined(GRASP_CAP)
  #undef GRASP_CAP
#endif
#if defined(_WIN32) && defined(UNSCREW)
  #undef UNSCREW
#endif
#if defined(_WIN32) && defined(RELEASE_CAP)
  #undef RELEASE_CAP
#endif
#if defined(_WIN32) && defined(RELEASE_BOTTLE)
  #undef RELEASE_BOTTLE
#endif

  enum {
    STATUS = 0u,
    STOP = 1u,
    CLEAR_ESTOP = 2u,
    HOME_HANDS = 3u,
    RUN_BOTTLE_CAP_SEQUENCE = 10u,
    MOVE_LEFT_PREGRASP = 20u,
    GRASP_BOTTLE = 21u,
    MOVE_RIGHT_PREGRASP = 30u,
    GRASP_CAP = 31u,
    UNSCREW = 32u,
    RELEASE_CAP = 33u,
    RELEASE_BOTTLE = 34u,
  };


  typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TaskCommand_

typedef ::bimanual_drinking_v5_msgs::TaskCommand_<std::allocator<void> > TaskCommand;

typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::TaskCommand > TaskCommandPtr;
typedef boost::shared_ptr< ::bimanual_drinking_v5_msgs::TaskCommand const> TaskCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator1> & lhs, const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command == rhs.command &&
    lhs.speed_scale == rhs.speed_scale &&
    lhs.plan_only == rhs.plan_only;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator1> & lhs, const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bimanual_drinking_v5_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9e74ce5044da031d687036e93905cdb";
  }

  static const char* value(const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9e74ce5044da031ULL;
  static const uint64_t static_value2 = 0xd687036e93905cdbULL;
};

template<class ContainerAllocator>
struct DataType< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bimanual_drinking_v5_msgs/TaskCommand";
  }

  static const char* value(const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STATUS=0\n"
"uint8 STOP=1\n"
"uint8 CLEAR_ESTOP=2\n"
"uint8 HOME_HANDS=3\n"
"uint8 RUN_BOTTLE_CAP_SEQUENCE=10\n"
"uint8 MOVE_LEFT_PREGRASP=20\n"
"uint8 GRASP_BOTTLE=21\n"
"uint8 MOVE_RIGHT_PREGRASP=30\n"
"uint8 GRASP_CAP=31\n"
"uint8 UNSCREW=32\n"
"uint8 RELEASE_CAP=33\n"
"uint8 RELEASE_BOTTLE=34\n"
"std_msgs/Header header\n"
"uint8 command\n"
"float32 speed_scale\n"
"bool plan_only\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
      stream.next(m.speed_scale);
      stream.next(m.plan_only);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bimanual_drinking_v5_msgs::TaskCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed_scale: ";
    Printer<float>::stream(s, indent + "  ", v.speed_scale);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "plan_only: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan_only);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIMANUAL_DRINKING_V5_MSGS_MESSAGE_TASKCOMMAND_H
