; Auto-generated. Do not edit!


(cl:in-package mujoco_ros_msgs-msg)


;//! \htmlinclude StepGoal.msg.html

(cl:defclass <StepGoal> (roslisp-msg-protocol:ros-message)
  ((num_steps
    :reader num_steps
    :initarg :num_steps
    :type cl:fixnum
    :initform 0))
)

(cl:defclass StepGoal (<StepGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StepGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StepGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mujoco_ros_msgs-msg:<StepGoal> is deprecated: use mujoco_ros_msgs-msg:StepGoal instead.")))

(cl:ensure-generic-function 'num_steps-val :lambda-list '(m))
(cl:defmethod num_steps-val ((m <StepGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mujoco_ros_msgs-msg:num_steps-val is deprecated.  Use mujoco_ros_msgs-msg:num_steps instead.")
  (num_steps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StepGoal>) ostream)
  "Serializes a message object of type '<StepGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_steps)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_steps)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StepGoal>) istream)
  "Deserializes a message object of type '<StepGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'num_steps)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'num_steps)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StepGoal>)))
  "Returns string type for a message object of type '<StepGoal>"
  "mujoco_ros_msgs/StepGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StepGoal)))
  "Returns string type for a message object of type 'StepGoal"
  "mujoco_ros_msgs/StepGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StepGoal>)))
  "Returns md5sum for a message object of type '<StepGoal>"
  "225dddb47d0d74321c7417323fd734df")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StepGoal)))
  "Returns md5sum for a message object of type 'StepGoal"
  "225dddb47d0d74321c7417323fd734df")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StepGoal>)))
  "Returns full string definition for message of type '<StepGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint16 num_steps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StepGoal)))
  "Returns full string definition for message of type 'StepGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint16 num_steps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StepGoal>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StepGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'StepGoal
    (cl:cons ':num_steps (num_steps msg))
))
