; Auto-generated. Do not edit!


(cl:in-package mujoco_ros_msgs-msg)


;//! \htmlinclude StepResult.msg.html

(cl:defclass <StepResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass StepResult (<StepResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StepResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StepResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mujoco_ros_msgs-msg:<StepResult> is deprecated: use mujoco_ros_msgs-msg:StepResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <StepResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mujoco_ros_msgs-msg:success-val is deprecated.  Use mujoco_ros_msgs-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StepResult>) ostream)
  "Serializes a message object of type '<StepResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StepResult>) istream)
  "Deserializes a message object of type '<StepResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StepResult>)))
  "Returns string type for a message object of type '<StepResult>"
  "mujoco_ros_msgs/StepResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StepResult)))
  "Returns string type for a message object of type 'StepResult"
  "mujoco_ros_msgs/StepResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StepResult>)))
  "Returns md5sum for a message object of type '<StepResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StepResult)))
  "Returns md5sum for a message object of type 'StepResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StepResult>)))
  "Returns full string definition for message of type '<StepResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StepResult)))
  "Returns full string definition for message of type 'StepResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StepResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StepResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StepResult
    (cl:cons ':success (success msg))
))
