; Auto-generated. Do not edit!


(cl:in-package mujoco_ros_msgs-msg)


;//! \htmlinclude StepFeedback.msg.html

(cl:defclass <StepFeedback> (roslisp-msg-protocol:ros-message)
  ((steps_left
    :reader steps_left
    :initarg :steps_left
    :type cl:fixnum
    :initform 0))
)

(cl:defclass StepFeedback (<StepFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StepFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StepFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mujoco_ros_msgs-msg:<StepFeedback> is deprecated: use mujoco_ros_msgs-msg:StepFeedback instead.")))

(cl:ensure-generic-function 'steps_left-val :lambda-list '(m))
(cl:defmethod steps_left-val ((m <StepFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mujoco_ros_msgs-msg:steps_left-val is deprecated.  Use mujoco_ros_msgs-msg:steps_left instead.")
  (steps_left m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StepFeedback>) ostream)
  "Serializes a message object of type '<StepFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'steps_left)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'steps_left)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StepFeedback>) istream)
  "Deserializes a message object of type '<StepFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'steps_left)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'steps_left)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StepFeedback>)))
  "Returns string type for a message object of type '<StepFeedback>"
  "mujoco_ros_msgs/StepFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StepFeedback)))
  "Returns string type for a message object of type 'StepFeedback"
  "mujoco_ros_msgs/StepFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StepFeedback>)))
  "Returns md5sum for a message object of type '<StepFeedback>"
  "a556a7a610310d9e0a8b278ad1208e9d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StepFeedback)))
  "Returns md5sum for a message object of type 'StepFeedback"
  "a556a7a610310d9e0a8b278ad1208e9d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StepFeedback>)))
  "Returns full string definition for message of type '<StepFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint16 steps_left~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StepFeedback)))
  "Returns full string definition for message of type 'StepFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint16 steps_left~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StepFeedback>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StepFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'StepFeedback
    (cl:cons ':steps_left (steps_left msg))
))
