// Generated by gencpp from file armcontrol/MoveToTargetRequest.msg
// DO NOT EDIT!


#ifndef ARMCONTROL_MESSAGE_MOVETOTARGETREQUEST_H
#define ARMCONTROL_MESSAGE_MOVETOTARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armcontrol
{
template <class ContainerAllocator>
struct MoveToTargetRequest_
{
  typedef MoveToTargetRequest_<ContainerAllocator> Type;

  MoveToTargetRequest_()
    : arm()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  MoveToTargetRequest_(const ContainerAllocator& _alloc)
    : arm(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _arm_type;
  _arm_type arm;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToTargetRequest_

typedef ::armcontrol::MoveToTargetRequest_<std::allocator<void> > MoveToTargetRequest;

typedef boost::shared_ptr< ::armcontrol::MoveToTargetRequest > MoveToTargetRequestPtr;
typedef boost::shared_ptr< ::armcontrol::MoveToTargetRequest const> MoveToTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armcontrol::MoveToTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::armcontrol::MoveToTargetRequest_<ContainerAllocator1> & lhs, const ::armcontrol::MoveToTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.arm == rhs.arm &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::armcontrol::MoveToTargetRequest_<ContainerAllocator1> & lhs, const ::armcontrol::MoveToTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace armcontrol

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "350d48a9c3526923e8d975c2c3cd295a";
  }

  static const char* value(const ::armcontrol::MoveToTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x350d48a9c3526923ULL;
  static const uint64_t static_value2 = 0xe8d975c2c3cd295aULL;
};

template<class ContainerAllocator>
struct DataType< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armcontrol/MoveToTargetRequest";
  }

  static const char* value(const ::armcontrol::MoveToTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string arm\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::armcontrol::MoveToTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arm);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armcontrol::MoveToTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::armcontrol::MoveToTargetRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "arm: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.arm);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROL_MESSAGE_MOVETOTARGETREQUEST_H
