// Generated by gencpp from file armcontrol/MoveToTargetResponse.msg
// DO NOT EDIT!


#ifndef ARMCONTROL_MESSAGE_MOVETOTARGETRESPONSE_H
#define ARMCONTROL_MESSAGE_MOVETOTARGETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace armcontrol
{
template <class ContainerAllocator>
struct MoveToTargetResponse_
{
  typedef MoveToTargetResponse_<ContainerAllocator> Type;

  MoveToTargetResponse_()
    {
    }
  MoveToTargetResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToTargetResponse_

typedef ::armcontrol::MoveToTargetResponse_<std::allocator<void> > MoveToTargetResponse;

typedef boost::shared_ptr< ::armcontrol::MoveToTargetResponse > MoveToTargetResponsePtr;
typedef boost::shared_ptr< ::armcontrol::MoveToTargetResponse const> MoveToTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::armcontrol::MoveToTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace armcontrol

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::armcontrol::MoveToTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "armcontrol/MoveToTargetResponse";
  }

  static const char* value(const ::armcontrol::MoveToTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::armcontrol::MoveToTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::armcontrol::MoveToTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::armcontrol::MoveToTargetResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ARMCONTROL_MESSAGE_MOVETOTARGETRESPONSE_H
