// Generated by gencpp from file armcontrol/MoveToTarget.msg
// DO NOT EDIT!


#ifndef ARMCONTROL_MESSAGE_MOVETOTARGET_H
#define ARMCONTROL_MESSAGE_MOVETOTARGET_H

#include <ros/service_traits.h>


#include <armcontrol/MoveToTargetRequest.h>
#include <armcontrol/MoveToTargetResponse.h>


namespace armcontrol
{

struct MoveToTarget
{

typedef MoveToTargetRequest Request;
typedef MoveToTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToTarget
} // namespace armcontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::armcontrol::MoveToTarget > {
  static const char* value()
  {
    return "350d48a9c3526923e8d975c2c3cd295a";
  }

  static const char* value(const ::armcontrol::MoveToTarget&) { return value(); }
};

template<>
struct DataType< ::armcontrol::MoveToTarget > {
  static const char* value()
  {
    return "armcontrol/MoveToTarget";
  }

  static const char* value(const ::armcontrol::MoveToTarget&) { return value(); }
};


// service_traits::MD5Sum< ::armcontrol::MoveToTargetRequest> should match
// service_traits::MD5Sum< ::armcontrol::MoveToTarget >
template<>
struct MD5Sum< ::armcontrol::MoveToTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::armcontrol::MoveToTarget >::value();
  }
  static const char* value(const ::armcontrol::MoveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::armcontrol::MoveToTargetRequest> should match
// service_traits::DataType< ::armcontrol::MoveToTarget >
template<>
struct DataType< ::armcontrol::MoveToTargetRequest>
{
  static const char* value()
  {
    return DataType< ::armcontrol::MoveToTarget >::value();
  }
  static const char* value(const ::armcontrol::MoveToTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::armcontrol::MoveToTargetResponse> should match
// service_traits::MD5Sum< ::armcontrol::MoveToTarget >
template<>
struct MD5Sum< ::armcontrol::MoveToTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::armcontrol::MoveToTarget >::value();
  }
  static const char* value(const ::armcontrol::MoveToTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::armcontrol::MoveToTargetResponse> should match
// service_traits::DataType< ::armcontrol::MoveToTarget >
template<>
struct DataType< ::armcontrol::MoveToTargetResponse>
{
  static const char* value()
  {
    return DataType< ::armcontrol::MoveToTarget >::value();
  }
  static const char* value(const ::armcontrol::MoveToTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARMCONTROL_MESSAGE_MOVETOTARGET_H
