// Generated by gencpp from file bimanual_drinking_v4_msgs/TaskCommand.msg
// DO NOT EDIT!


#ifndef BIMANUAL_DRINKING_V4_MSGS_MESSAGE_TASKCOMMAND_H
#define BIMANUAL_DRINKING_V4_MSGS_MESSAGE_TASKCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bimanual_drinking_v4_msgs
{
template <class ContainerAllocator>
struct TaskCommand_
{
  typedef TaskCommand_<ContainerAllocator> Type;

  TaskCommand_()
    : header()
    , command(0)
    , speed_scale(0.0)
    , use_relative_planning(false)  {
    }
  TaskCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command(0)
    , speed_scale(0.0)
    , use_relative_planning(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _command_type;
  _command_type command;

   typedef float _speed_scale_type;
  _speed_scale_type speed_scale;

   typedef uint8_t _use_relative_planning_type;
  _use_relative_planning_type use_relative_planning;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATUS)
  #undef STATUS
#endif
#if defined(_WIN32) && defined(CLEAR_ESTOP)
  #undef CLEAR_ESTOP
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(HOME)
  #undef HOME
#endif
#if defined(_WIN32) && defined(BOTTLE_PREGRASP)
  #undef BOTTLE_PREGRASP
#endif
#if defined(_WIN32) && defined(BOTTLE_GRASP)
  #undef BOTTLE_GRASP
#endif
#if defined(_WIN32) && defined(CAP_PREGRASP)
  #undef CAP_PREGRASP
#endif
#if defined(_WIN32) && defined(CAP_GRASP)
  #undef CAP_GRASP
#endif
#if defined(_WIN32) && defined(UNSCREW)
  #undef UNSCREW
#endif
#if defined(_WIN32) && defined(CAP_RETREAT)
  #undef CAP_RETREAT
#endif
#if defined(_WIN32) && defined(LIFT_BOTTLE)
  #undef LIFT_BOTTLE
#endif
#if defined(_WIN32) && defined(RETURN_HOME)
  #undef RETURN_HOME
#endif
#if defined(_WIN32) && defined(RUN_BOTTLE_CAP_SEQUENCE)
  #undef RUN_BOTTLE_CAP_SEQUENCE
#endif

  enum {
    STATUS = 0u,
    CLEAR_ESTOP = 1u,
    STOP = 2u,
    HOME = 10u,
    BOTTLE_PREGRASP = 20u,
    BOTTLE_GRASP = 21u,
    CAP_PREGRASP = 30u,
    CAP_GRASP = 31u,
    UNSCREW = 32u,
    CAP_RETREAT = 33u,
    LIFT_BOTTLE = 40u,
    RETURN_HOME = 50u,
    RUN_BOTTLE_CAP_SEQUENCE = 100u,
  };


  typedef boost::shared_ptr< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TaskCommand_

typedef ::bimanual_drinking_v4_msgs::TaskCommand_<std::allocator<void> > TaskCommand;

typedef boost::shared_ptr< ::bimanual_drinking_v4_msgs::TaskCommand > TaskCommandPtr;
typedef boost::shared_ptr< ::bimanual_drinking_v4_msgs::TaskCommand const> TaskCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator1> & lhs, const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command == rhs.command &&
    lhs.speed_scale == rhs.speed_scale &&
    lhs.use_relative_planning == rhs.use_relative_planning;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator1> & lhs, const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bimanual_drinking_v4_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17bd5cd1727d685e66c27d5606d0e4d0";
  }

  static const char* value(const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17bd5cd1727d685eULL;
  static const uint64_t static_value2 = 0x66c27d5606d0e4d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bimanual_drinking_v4_msgs/TaskCommand";
  }

  static const char* value(const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8 STATUS=0\n"
"uint8 CLEAR_ESTOP=1\n"
"uint8 STOP=2\n"
"uint8 HOME=10\n"
"uint8 BOTTLE_PREGRASP=20\n"
"uint8 BOTTLE_GRASP=21\n"
"uint8 CAP_PREGRASP=30\n"
"uint8 CAP_GRASP=31\n"
"uint8 UNSCREW=32\n"
"uint8 CAP_RETREAT=33\n"
"uint8 LIFT_BOTTLE=40\n"
"uint8 RETURN_HOME=50\n"
"uint8 RUN_BOTTLE_CAP_SEQUENCE=100\n"
"uint8 command\n"
"float32 speed_scale\n"
"bool use_relative_planning\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command);
      stream.next(m.speed_scale);
      stream.next(m.use_relative_planning);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bimanual_drinking_v4_msgs::TaskCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed_scale: ";
    Printer<float>::stream(s, indent + "  ", v.speed_scale);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_relative_planning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_relative_planning);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIMANUAL_DRINKING_V4_MSGS_MESSAGE_TASKCOMMAND_H
